name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_HECTOR }}
          REMOTE_HOST: ${{ secrets.DNS_HECTOR }}
          REMOTE_USER: ${{ secrets.USERN }}
          TARGET: ${{ secrets.DIREC }}

      - name: Deploy to Server 2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_JOSE }}
          REMOTE_HOST: ${{ secrets.DNS_JOSE }}
          REMOTE_USER: ${{ secrets.USERN }}
          TARGET: ${{ secrets.DIREC }}
      
      - name: Deploy to Server 3
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_ISA }}
          REMOTE_HOST: ${{ secrets.DNS_ISA }}
          REMOTE_USER: ${{ secrets.USERN }}
          TARGET: ${{ secrets.DIREC }}

      - name: Deploy to Server 4
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_ALEJO }}
          REMOTE_HOST: ${{ secrets.DNS_ALEJO }}
          REMOTE_USER: ${{ secrets.USERN }}
          TARGET: ${{ secrets.DIREC }}